"""Canonical public surface of the ``maistro.extensions`` package: the
governed registry, activation flow, dependency resolution, contract
negotiation, preflight, and certification (M9-B/M9-C/M9-H3, issues
#952/#953/#956/#975).

This package carries the extension surface of epic #938, in four layers:

- **M9-A2 runtime contract (#950, ADR-104)**: the interfaces through which an
  extension is activated, invoked, and deactivated, and the least-authority
  object it is handed while doing so. The contract, in one paragraph: an
  extension declares its maximum authority (config keys, services, effects)
  in an :class:`ExtensionDescriptor`; the host runtime composes that
  declaration with what it is willing to grant into one
  :class:`ExtensionContext` per invocation; and every authority-sensitive
  operation the extension can perform from that context crosses a canonical
  seam — governed ``Capability → Provider → Binding → Invocation`` dispatch
  for effects, the canonical ``Run/NodeRun/Attempt`` fence for cancellation,
  and correlated canonical events for progress and provenance. There is no
  ambient container access: a context holds no store, session, or container
  handle, and a refused seam raises instead of returning something empty.
  This layer deliberately does not define a scheduler, run store, execution
  authority, or extension loading/manifest machinery (manifest schema: #949).
  Physical execution truth remains owned by the canonical
  ``Graph → Run → NodeRun → Attempt`` chain; hosts drive extensions through
  :class:`ExtensionHost` from inside their existing Attempt execution.

- **M9-B1 registry (issue #952)**: immutable install records with publisher
  identity, package digest/signature metadata, manifest snapshots, catalog
  provenance and durable trust evidence; the append-only
  :class:`ExtensionInstallStore` protocol with its in-memory reference and
  SQLite durable twin. The inspect→authorize→install flow (#953) and the
  pin/upgrade/rollback lifecycle (#954) build on these records.

- **M9-B2 activation (issue #953)**: the governed install state machine —
  the pure evaluation modules (manifest, compatibility, trust, authority),
  the activation store seam, and :class:`ExtensionInstallService`. Nothing in
  this package ever imports extension code; activation runs only through the
  host-supplied :class:`ExtensionCodeLoader`, and only after explicit
  authorization. The post-install lifecycle (#954) lives on the same
  service: disable/re-enable, rollback to a previously authorized version,
  terminal removal, and operator pins that fence version moves — every step
  audited, none ever re-running the loader or widening a grant.
- **M9-C1 policy (issue #955, ``maistro.extensions.compat``)**: decides
  whether an extension's declared contract, features, and deprecation posture
  are compatible with this host — from metadata alone, before any code
  import.
- **M9-C2 resolution (issue #956)**: strict semantic-version ranges
  (``semver``), a deterministic resolver producing a reproducible
  :class:`LockState` (``resolution``), and lock-driven reinstall through the
  install store (:func:`materialize_lock`).
- **M9-I3 operational views (issue #978)**: the truthful health projection
  (``health``) — error taxonomy with provenance, host-recorded invocation
  evidence, durable operator enable/disable/quarantine state, per-version
  usage digests with ranking and SLO error-budget inputs, and the durable
  health store (``sqlite_health_store``) that makes projected health survive
  a restart.
- **M9-H3 certification (issue #975)**: the pre-publication workflow —
  package structure validation, static public-import and security scans,
  conformance-suite orchestration, Ed25519 sealing of the report digest,
  and truthful certification reports whose claims can only come from checks
  that executed and passed (:mod:`maistro.extensions.certification`).
  Certification is install-time *evidence* (a trust-claim input), never an
  authorization by itself.
- **M9-I2 metering (issue #977)**: usage attribution and Workspace/org quota
  enforcement at the extension seam (``metering``) — physical usage recorded
  once against canonical Invocation ids, nested delegation lineage, atomic
  reservation/refund/correction semantics, and aggregation by Workspace,
  extension, publisher, capability and time window. Attribution only: the
  canonical provider totals stay with ``maistro.quota``.
- **M9-C3 preflight (issue #957)**: host-upgrade compatibility preflight —
  :func:`run_preflight` evaluates the installed lock state against a target
  host contract (:class:`TargetHostContract`) built from public manifest
  metadata only, naming compatible, deprecated, migration-required and
  blocking extensions before the upgrade is applied. The target release is
  data, never imported code; nothing is activated.
- **M9-F2 UI components (issue #967)**: the governed UI/A2UI component
  contract (:mod:`maistro.extensions.ui`) — declarative component catalogs
  that project canonical state through a closed binding allowlist, route
  mutating actions to governed server seams only, enforce availability
  server-side, and carry sandbox policy and provenance on every render.

No layer executes extension code: verification, evaluation, authorization,
resolution, contract negotiation, certification and metering all operate on
bytes, declarations, identity and amounts alone.

Naming note: ``ExtensionLifecycleError`` is the governed-install failure base
(#952/#953). The #950 hook-failure wrapper — the error raised when an
extension's own ``activate``/``invoke``/``deactivate`` hook raises — is
:class:`ExtensionHookError`, a distinct ``ExtensionContractError`` subclass.
"""

from __future__ import annotations

from maistro.extensions.authority import (
    AuthorityBaseline,
    AuthorityDelta,
    compute_authority_delta,
    normalize_permission,
)
from maistro.extensions.certification import (
    BUNDLE_FORMAT,
    CERTIFICATION_FORMAT,
    CERTIFIER_VERSION,
    CONFORMANCE_CHECK_ID,
    ENTRYPOINTS_CHECK_ID,
    MANIFEST_PROFILE,
    PUBLIC_IMPORTS_CHECK_ID,
    PUBLICATION_PROFILE,
    SEAL_FORMAT,
    SECURITY_SCAN_CHECK_ID,
    STRUCTURE_CHECK_ID,
    CertificationCheck,
    CertificationEnvironment,
    CertificationError,
    CertificationInvalid,
    CertificationPackageMismatch,
    CertificationProfile,
    CertificationReport,
    CertificationSeal,
    CertificationSubject,
    CheckOutcome,
    CheckResult,
    ConformanceCheck,
    ConformanceOutcome,
    ConformanceSuite,
    DuplicateCheckError,
    EntryPointPresenceCheck,
    ExtensionBundle,
    ImportPolicy,
    PackageStructureCheck,
    PublicImportCheck,
    SecurityScanCheck,
    UnboundCheckError,
    bundle_digest,
    certification_as_trust_claim,
    certify,
    detect_environment,
    render_summary,
    report_digest,
    report_from_json,
    report_to_json,
    seal_from_json,
    seal_to_json,
    sign_certification,
    verify_certification,
    verify_certified_package,
)
from maistro.extensions.compat import (
    CONTRACT_VERSION,
    FEATURE_DEPRECATED,
    FEATURE_REMOVED,
    FEATURE_STATUSES,
    FEATURE_SUPPORTED,
    HOST_FEATURES,
    SUPPORTED_CONTRACT_MAJORS,
    CompatError,
    CompatibilityReport,
    CompatMetadataError,
    ContractRange,
    ContractVersion,
    Degradation,
    DeprecationNotice,
    ExtensionCompatMetadata,
    FeatureStatus,
    FeatureSupport,
    HostContractMetadata,
    IncompatibleContract,
    Verdict,
    ensure_compatible,
    negotiate,
    parse_compat_metadata,
    parse_contract_range,
    parse_contract_version,
    parse_feature_status,
)
from maistro.extensions.compatibility import (
    CompatibilityPolicy,
    evaluate_compatibility,
)
from maistro.extensions.context import (
    EffectDispatcher,
    EffectReceipt,
    ExtensionCancellation,
    ExtensionConfigView,
    ExtensionContext,
    ExtensionContractUnavailableError,
    ExtensionProgress,
    ProgressReporter,
    UngrantedProgressReporter,
)
from maistro.extensions.effective_authority import (
    CallerAuthority,
    EffectiveAuthority,
    ExtensionAuthorityEvidence,
    ExtensionAuthorityInputs,
    HostExtensionPolicy,
    PermissionDenial,
    PublisherTrust,
    TrustTier,
    WorkspaceExtensionPolicy,
    compute_effective_authority,
    extension_family,
    resolve_publisher_trust,
)
from maistro.extensions.errors import (
    ConfigurationKeyNotDeclared,
    EffectNotDeclared,
    ExtensionCancelled,
    ExtensionContractError,
    ExtensionHookError,
    ScopeMismatch,
    ServiceNotGranted,
)
from maistro.extensions.health import (
    HEALTH_WINDOW,
    HEALTHY_STATES,
    DependencyReadiness,
    ExtensionErrorKind,
    ExtensionErrorRecord,
    ExtensionHealth,
    ExtensionHealthService,
    ExtensionHealthStore,
    ExtensionObservation,
    ExtensionOperationalState,
    ExtensionOperationalStatus,
    ExtensionOperatorAction,
    ExtensionOperatorState,
    ExtensionUsageDigest,
    InMemoryExtensionHealthStore,
    ObservationOutcome,
    OperatorDecision,
    RankingMetric,
    SloPosition,
    TelemetryExport,
    dependency_readiness,
    digest_observations,
    evaluate_health,
    latest_decision,
    operator_state_for,
    project_operational_status,
    rank_digests,
    slo_position,
    state_for_action,
)
from maistro.extensions.host import (
    EffectRoute,
    EventStoreProgressSink,
    ExtensionHost,
    GovernedEffectRoute,
    ProgressSink,
)
from maistro.extensions.identity import (
    ExtensionDescriptor,
    ExtensionIdentity,
    InvocationScope,
)
from maistro.extensions.isolation import (
    DEFAULT_MIN_TIER,
    FILESYSTEM_READ_PERMISSION,
    FILESYSTEM_WRITE_PERMISSION,
    NETWORK_OUTBOUND_PERMISSION,
    REAL_ISOLATION_TIERS,
    ExtensionIsolationError,
    ExtensionIsolationProfile,
    ExtensionIsolationRefused,
    ExtensionRiskTier,
    ExtensionSandboxExecutionFailure,
    ExtensionSandboxOutcome,
    ExtensionSandboxPolicy,
    ExtensionSandboxRunner,
    ExtensionSandboxStartFailure,
    ExtensionSandboxViolation,
    InProcessExtensionLoader,
    SandboxViolationLog,
    ViolationKind,
    build_sandbox_config,
    risk_tier_for,
    select_isolation_profile,
)
from maistro.extensions.lifecycle import (
    ExtensionLifecycle,
    run_activation,
    run_deactivation,
    run_invocation,
)
from maistro.extensions.manifest import (
    SUPPORTED_MANIFEST_VERSION,
    assert_snapshot_intact,
    inspect_manifest,
    sha256_hex,
    verify_package_payload,
)
from maistro.extensions.metering import (
    AttributionDimension,
    ExtensionMeter,
    ExtensionMeteringError,
    ExtensionQuotaBalance,
    ExtensionQuotaConflict,
    ExtensionQuotaDenied,
    ExtensionQuotaLedger,
    ExtensionQuotaPolicy,
    ExtensionQuotaRequest,
    ExtensionUsageAmounts,
    ExtensionUsageConflict,
    ExtensionUsageEvent,
    UsageTotals,
)
from maistro.extensions.packs import (
    SUPPORTED_PACK_MANIFEST_VERSION,
    InstallablePackRegistry,
    PackAsset,
    PackAssetKind,
    PackAssetUnknown,
    PackContractError,
    PackDisabledError,
    PackGraphDefinition,
    PackGraphNode,
    PackIdentityConflict,
    PackIncompatible,
    PackInstallRecord,
    PackManifest,
    PackManifestRejected,
    PackPersonaDefinition,
    PackProvenance,
    PackRubricDefinition,
    PackState,
    evaluate_pack_compatibility,
    inspect_pack_manifest,
    instantiate_graph_asset,
    instantiate_persona_asset,
    instantiate_rubric_asset,
    pack_extension_view,
)
from maistro.extensions.preflight import (
    ExtensionStatus,
    PreflightPolicy,
    PreflightReport,
    TargetHostContract,
    run_preflight,
)
from maistro.extensions.resolution import (
    LOCK_FORMAT,
    ROOT_REQUEST_ORIGIN,
    SELECTION_POLICY,
    CatalogEntry,
    ConstraintRecord,
    DependencyCycle,
    ExtensionCatalog,
    ExtensionDependency,
    LockArtifacts,
    LockDiff,
    LockEntry,
    LockFormatError,
    LockKind,
    LockState,
    MissingLockArtifacts,
    RejectedCandidate,
    ResolutionConflict,
    ResolutionError,
    RootRequest,
    SelectionExplanation,
    SkippedOptional,
    UnresolvableDependency,
    diff_locks,
    materialize_lock,
    resolve_lock,
)
from maistro.extensions.semver import (
    InvalidSemanticVersion,
    InvalidVersionRange,
    SemVer,
    VersionRange,
    parse_range,
)
from maistro.extensions.service import (
    ExtensionCodeLoader,
    ExtensionInstallService,
    LoadedExtension,
    UnwiredExtensionLoader,
)
from maistro.extensions.sqlite_health_store import SqliteExtensionHealthStore
from maistro.extensions.sqlite_store import SqliteExtensionInstallStore
from maistro.extensions.store import (
    TRUST_POLICY,
    ActivationCallback,
    ExtensionInstallStore,
    ExtensionStore,
    InMemoryExtensionInstallStore,
    InMemoryExtensionStore,
)
from maistro.extensions.trust import TrustPolicy, TrustReport, evaluate_trust

# NOTE: both `compat` (M9-C1 negotiation, #955) and `compatibility` (M9-B2
# activation, #953) define a class named `CompatibilityReport`. The package
# binds the M9-C1 negotiation report; the activation-layer report stays on
# its module path (`maistro.extensions.compatibility.CompatibilityReport`),
# which is how its in-tree consumers already import it.
from maistro.extensions.types import (
    DIGEST_ALGORITHM,
    TERMINAL_STATES,
    TRANSITIONS,
    ArtifactMismatch,
    ExtensionEntryPoint,
    ExtensionIdentityConflict,
    ExtensionInstallRecord,
    ExtensionLifecycleError,
    ExtensionManifest,
    ExtensionPackage,
    ExtensionRegistryError,
    ExtensionScope,
    ExtensionState,
    ExtensionTransition,
    InspectionConflict,
    InstallRecord,
    InstallRequest,
    InvalidTransition,
    ManifestRejected,
    ManifestSnapshot,
    PackageDigestMismatch,
    PackageIdentity,
    PackageSignatureInvalid,
    PublisherIdentity,
    PublisherKeyConflict,
    RegistryProvenance,
    TrustClaim,
    TrustEvidence,
    UnknownInstall,
    UnknownPublisher,
    VersionPinned,
    canonical_install_payload,
    identity_key,
    manifest_snapshot,
)
from maistro.extensions.ui import (
    ActionAvailability,
    ActionUnavailable,
    CatalogRejected,
    ClientStateRejected,
    ComponentAsset,
    ComponentProvenance,
    DataBinding,
    GovernedActionCall,
    GovernedRoute,
    RenderedComponent,
    RouteParam,
    SandboxPolicy,
    UiAction,
    UiComponentDefinition,
    UiComponentManifest,
    UiExtensionError,
    UiProjectionService,
    UnknownAction,
    UnknownCatalog,
    UnknownComponent,
    assert_ui_snapshot_intact,
    inspect_ui_manifest,
    verify_component_asset,
)

__all__ = [
    "BUNDLE_FORMAT",
    "CERTIFICATION_FORMAT",
    "CERTIFIER_VERSION",
    "CONFORMANCE_CHECK_ID",
    "CONTRACT_VERSION",
    "DEFAULT_MIN_TIER",
    "DIGEST_ALGORITHM",
    "ENTRYPOINTS_CHECK_ID",
    "FEATURE_DEPRECATED",
    "FEATURE_REMOVED",
    "FEATURE_STATUSES",
    "FEATURE_SUPPORTED",
    "FILESYSTEM_READ_PERMISSION",
    "FILESYSTEM_WRITE_PERMISSION",
    "HEALTHY_STATES",
    "HEALTH_WINDOW",
    "HOST_FEATURES",
    "LOCK_FORMAT",
    "MANIFEST_PROFILE",
    "NETWORK_OUTBOUND_PERMISSION",
    "PUBLICATION_PROFILE",
    "PUBLIC_IMPORTS_CHECK_ID",
    "REAL_ISOLATION_TIERS",
    "ROOT_REQUEST_ORIGIN",
    "SEAL_FORMAT",
    "SECURITY_SCAN_CHECK_ID",
    "SELECTION_POLICY",
    "STRUCTURE_CHECK_ID",
    "SUPPORTED_CONTRACT_MAJORS",
    "SUPPORTED_MANIFEST_VERSION",
    "SUPPORTED_PACK_MANIFEST_VERSION",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "TRUST_POLICY",
    "ActionAvailability",
    "ActionUnavailable",
    "ActivationCallback",
    "ArtifactMismatch",
    "AttributionDimension",
    "AuthorityBaseline",
    "AuthorityDelta",
    "CallerAuthority",
    "CatalogEntry",
    "CatalogRejected",
    "CertificationCheck",
    "CertificationEnvironment",
    "CertificationError",
    "CertificationInvalid",
    "CertificationPackageMismatch",
    "CertificationProfile",
    "CertificationReport",
    "CertificationSeal",
    "CertificationSubject",
    "CheckOutcome",
    "CheckResult",
    "ClientStateRejected",
    "CompatError",
    "CompatMetadataError",
    "CompatibilityPolicy",
    "CompatibilityReport",
    "ComponentAsset",
    "ComponentProvenance",
    "ConfigurationKeyNotDeclared",
    "ConformanceCheck",
    "ConformanceOutcome",
    "ConformanceSuite",
    "ConstraintRecord",
    "ContractRange",
    "ContractVersion",
    "DataBinding",
    "Degradation",
    "DependencyCycle",
    "DependencyReadiness",
    "DeprecationNotice",
    "DuplicateCheckError",
    "EffectDispatcher",
    "EffectNotDeclared",
    "EffectReceipt",
    "EffectRoute",
    "EffectiveAuthority",
    "EntryPointPresenceCheck",
    "EventStoreProgressSink",
    "ExtensionAuthorityEvidence",
    "ExtensionAuthorityInputs",
    "ExtensionBundle",
    "ExtensionCancellation",
    "ExtensionCancelled",
    "ExtensionCatalog",
    "ExtensionCodeLoader",
    "ExtensionCompatMetadata",
    "ExtensionConfigView",
    "ExtensionContext",
    "ExtensionContractError",
    "ExtensionContractUnavailableError",
    "ExtensionDependency",
    "ExtensionDescriptor",
    "ExtensionEntryPoint",
    "ExtensionErrorKind",
    "ExtensionErrorRecord",
    "ExtensionHealth",
    "ExtensionHealthService",
    "ExtensionHealthStore",
    "ExtensionHookError",
    "ExtensionHost",
    "ExtensionIdentity",
    "ExtensionIdentityConflict",
    "ExtensionInstallRecord",
    "ExtensionInstallService",
    "ExtensionInstallStore",
    "ExtensionIsolationError",
    "ExtensionIsolationProfile",
    "ExtensionIsolationRefused",
    "ExtensionLifecycle",
    "ExtensionLifecycleError",
    "ExtensionManifest",
    "ExtensionMeter",
    "ExtensionMeteringError",
    "ExtensionObservation",
    "ExtensionOperationalState",
    "ExtensionOperationalStatus",
    "ExtensionOperatorAction",
    "ExtensionOperatorState",
    "ExtensionPackage",
    "ExtensionProgress",
    "ExtensionQuotaBalance",
    "ExtensionQuotaConflict",
    "ExtensionQuotaDenied",
    "ExtensionQuotaLedger",
    "ExtensionQuotaPolicy",
    "ExtensionQuotaRequest",
    "ExtensionRegistryError",
    "ExtensionRiskTier",
    "ExtensionSandboxExecutionFailure",
    "ExtensionSandboxOutcome",
    "ExtensionSandboxPolicy",
    "ExtensionSandboxRunner",
    "ExtensionSandboxStartFailure",
    "ExtensionSandboxViolation",
    "ExtensionScope",
    "ExtensionState",
    "ExtensionStatus",
    "ExtensionStore",
    "ExtensionTransition",
    "ExtensionUsageAmounts",
    "ExtensionUsageConflict",
    "ExtensionUsageDigest",
    "ExtensionUsageEvent",
    "FeatureStatus",
    "FeatureSupport",
    "GovernedActionCall",
    "GovernedEffectRoute",
    "GovernedRoute",
    "HostContractMetadata",
    "HostExtensionPolicy",
    "ImportPolicy",
    "InMemoryExtensionHealthStore",
    "InMemoryExtensionInstallStore",
    "InMemoryExtensionStore",
    "InProcessExtensionLoader",
    "IncompatibleContract",
    "InspectionConflict",
    "InstallRecord",
    "InstallRequest",
    "InstallablePackRegistry",
    "InvalidSemanticVersion",
    "InvalidTransition",
    "InvalidVersionRange",
    "InvocationScope",
    "LoadedExtension",
    "LockArtifacts",
    "LockDiff",
    "LockEntry",
    "LockFormatError",
    "LockKind",
    "LockState",
    "ManifestRejected",
    "ManifestSnapshot",
    "MissingLockArtifacts",
    "ObservationOutcome",
    "OperatorDecision",
    "PackAsset",
    "PackAssetKind",
    "PackAssetUnknown",
    "PackContractError",
    "PackDisabledError",
    "PackGraphDefinition",
    "PackGraphNode",
    "PackIdentityConflict",
    "PackIncompatible",
    "PackInstallRecord",
    "PackManifest",
    "PackManifestRejected",
    "PackPersonaDefinition",
    "PackProvenance",
    "PackRubricDefinition",
    "PackState",
    "PackageDigestMismatch",
    "PackageIdentity",
    "PackageSignatureInvalid",
    "PackageStructureCheck",
    "PermissionDenial",
    "PreflightPolicy",
    "PreflightReport",
    "ProgressReporter",
    "ProgressSink",
    "PublicImportCheck",
    "PublisherIdentity",
    "PublisherKeyConflict",
    "PublisherTrust",
    "RankingMetric",
    "RegistryProvenance",
    "RejectedCandidate",
    "RenderedComponent",
    "ResolutionConflict",
    "ResolutionError",
    "RootRequest",
    "RouteParam",
    "SandboxPolicy",
    "SandboxViolationLog",
    "ScopeMismatch",
    "SecurityScanCheck",
    "SelectionExplanation",
    "SemVer",
    "ServiceNotGranted",
    "SkippedOptional",
    "SloPosition",
    "SqliteExtensionHealthStore",
    "SqliteExtensionInstallStore",
    "TargetHostContract",
    "TelemetryExport",
    "TrustClaim",
    "TrustEvidence",
    "TrustPolicy",
    "TrustReport",
    "TrustTier",
    "UiAction",
    "UiComponentDefinition",
    "UiComponentManifest",
    "UiExtensionError",
    "UiProjectionService",
    "UnboundCheckError",
    "UngrantedProgressReporter",
    "UnknownAction",
    "UnknownCatalog",
    "UnknownComponent",
    "UnknownInstall",
    "UnknownPublisher",
    "UnresolvableDependency",
    "UnwiredExtensionLoader",
    "UsageTotals",
    "Verdict",
    "VersionPinned",
    "VersionRange",
    "ViolationKind",
    "WorkspaceExtensionPolicy",
    "assert_snapshot_intact",
    "assert_ui_snapshot_intact",
    "build_sandbox_config",
    "bundle_digest",
    "canonical_install_payload",
    "certification_as_trust_claim",
    "certify",
    "compute_authority_delta",
    "compute_effective_authority",
    "dependency_readiness",
    "detect_environment",
    "diff_locks",
    "digest_observations",
    "ensure_compatible",
    "evaluate_compatibility",
    "evaluate_health",
    "evaluate_pack_compatibility",
    "evaluate_trust",
    "extension_family",
    "identity_key",
    "inspect_manifest",
    "inspect_pack_manifest",
    "inspect_ui_manifest",
    "instantiate_graph_asset",
    "instantiate_persona_asset",
    "instantiate_rubric_asset",
    "latest_decision",
    "manifest_snapshot",
    "materialize_lock",
    "negotiate",
    "normalize_permission",
    "operator_state_for",
    "pack_extension_view",
    "parse_compat_metadata",
    "parse_contract_range",
    "parse_contract_version",
    "parse_feature_status",
    "parse_range",
    "project_operational_status",
    "rank_digests",
    "render_summary",
    "report_digest",
    "report_from_json",
    "report_to_json",
    "resolve_lock",
    "resolve_publisher_trust",
    "risk_tier_for",
    "run_activation",
    "run_deactivation",
    "run_invocation",
    "run_preflight",
    "seal_from_json",
    "seal_to_json",
    "select_isolation_profile",
    "sha256_hex",
    "sign_certification",
    "slo_position",
    "state_for_action",
    "verify_certification",
    "verify_certified_package",
    "verify_component_asset",
    "verify_package_payload",
]
