"""Transport-level browser policy checks using real Playwright routing.

The browser-use package and an LLM are intentionally not involved here. A
Chromium context is enough to prove the security boundary: requests go through
Playwright's route machinery, redirects are generated by a real HTTP server,
and a denied hop never reaches the destination server.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass
from typing import Any

import pytest

from maistro.security.outbound import configure_outbound_policy, reset_outbound_policy
from maistro.tools.browser.guard import ALLOWED, DENIED, BrowserNetworkGuard


@dataclass
class _HttpFixture:
    server: asyncio.base_events.Server
    port: int
    requests: list[str]

    @property
    def origin(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    async def close(self) -> None:
        self.server.close()
        await self.server.wait_closed()


async def _serve(
    response: Callable[[str], tuple[int, dict[str, str], bytes]],
) -> _HttpFixture:
    requests: list[str] = []

    async def handler(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            line = await reader.readline()
            path = line.decode("ascii", errors="replace").split(" ")[1]
            requests.append(path)
            while await reader.readline() != b"\r\n":
                pass
            status, headers, body = response(path)
            rendered_headers = {
                "Content-Length": str(len(body)),
                "Connection": "close",
                **headers,
            }
            head = "HTTP/1.1 {}\r\n{}\r\n\r\n".format(
                status,
                "\r\n".join(f"{key}: {value}" for key, value in rendered_headers.items()),
            )
            writer.write(head.encode("ascii") + body)
            await writer.drain()
        finally:
            writer.close()
            await writer.wait_closed()

    server = await asyncio.start_server(handler, "127.0.0.1", 0)
    socket = server.sockets[0]
    return _HttpFixture(server=server, port=int(socket.getsockname()[1]), requests=requests)


@pytest.fixture(autouse=True)
def _clean_policy() -> None:
    reset_outbound_policy()


@pytest.fixture
async def chromium_context() -> AsyncIterator[Any]:
    """Use Chromium when installed; browser-optional environments skip cleanly."""
    playwright_async_api = pytest.importorskip("playwright.async_api")
    playwright = await playwright_async_api.async_playwright().start()
    browser = None
    try:
        try:
            browser = await playwright.chromium.launch(headless=True)
        except Exception as exc:  # pragma: no cover - depends on host binaries
            pytest.skip(f"Chromium is unavailable: {exc}")
        context = await browser.new_context(service_workers="block")
        try:
            yield context
        finally:
            await context.close()
    finally:
        if browser is not None:
            await browser.close()
        await playwright.stop()


def _playwright_error() -> type[Exception]:
    from playwright.async_api import Error

    return Error


@pytest.mark.scope("integration")
async def test_real_chromium_rechecks_a_redirect_before_the_private_connection(
    chromium_context: Any,
) -> None:
    """A real redirect hop is routed and denied before the second server sees it."""
    private = await _serve(lambda _path: (200, {}, b"should never be reached"))
    public = await _serve(
        lambda path: (
            (
                302,
                {"Location": f"{private.origin}/metadata"},
                b"redirecting",
            )
            if path == "/redirect"
            else (200, {"Content-Type": "text/html"}, b"ok")
        )
    )
    configure_outbound_policy(public.origin)
    guard = BrowserNetworkGuard()
    await guard.attach(chromium_context)
    page = await chromium_context.new_page()

    try:
        with pytest.raises(_playwright_error()):
            await page.goto(f"{public.origin}/redirect", wait_until="load", timeout=5000)
    finally:
        await page.close()
        await public.close()
        await private.close()

    assert public.requests == ["/redirect"]
    assert private.requests == []
    assert [event.decision for event in guard.events] == [ALLOWED, DENIED]
    assert guard.events[-1].origin == private.origin


@pytest.mark.scope("integration")
async def test_real_chromium_follows_an_allowed_redirect_inside_the_guard(
    chromium_context: Any,
) -> None:
    target = await _serve(
        lambda _path: (200, {"Content-Type": "text/html"}, b"<title>target</title>ok")
    )
    source = await _serve(lambda _path: (302, {"Location": target.origin}, b"redirecting"))
    configure_outbound_policy(source.origin, target.origin)
    guard = BrowserNetworkGuard()
    await guard.attach(chromium_context)
    page = await chromium_context.new_page()

    try:
        response = await page.goto(source.origin, timeout=5000)
        assert response is not None and response.ok
    finally:
        await page.close()
        await source.close()
        await target.close()

    assert source.requests == ["/"]
    assert target.requests == ["/"]
    assert [event.decision for event in guard.events] == [ALLOWED, ALLOWED]


@pytest.mark.scope("integration")
async def test_real_chromium_denies_model_directed_loopback_before_connect(
    chromium_context: Any,
) -> None:
    guard = BrowserNetworkGuard()
    await guard.attach(chromium_context)
    page = await chromium_context.new_page()

    try:
        with pytest.raises(_playwright_error()):
            await page.goto("http://127.0.0.1:9/model-invented", timeout=5000)
    finally:
        await page.close()

    assert guard.denied_events()[-1].origin == "http://127.0.0.1:9"


@pytest.mark.scope("integration")
async def test_real_chromium_can_read_only_the_configured_origin(
    chromium_context: Any,
) -> None:
    allowed = await _serve(
        lambda _path: (200, {"Content-Type": "text/html"}, b"<title>allowed</title>ok")
    )
    other = await _serve(lambda _path: (200, {}, b"should not be reached"))
    configure_outbound_policy(allowed.origin)
    guard = BrowserNetworkGuard()
    await guard.attach(chromium_context)
    page = await chromium_context.new_page()

    try:
        response = await page.goto(allowed.origin, timeout=5000)
        assert response is not None and response.ok
        with pytest.raises(_playwright_error()):
            await page.goto(other.origin, timeout=5000)
    finally:
        await page.close()
        await allowed.close()
        await other.close()

    assert allowed.requests == ["/"]
    assert other.requests == []
    assert [event.decision for event in guard.events] == [ALLOWED, DENIED]
