"""One governed image egress: Binding -> Invocation -> approved Provider (#286).

Mirrors :mod:`maistro.capabilities.model_chat`. This module owns no HTTP: the
Binding must match its registered record in the effect context's Binding store
and authorize the ``image.generate`` capability; policy and
credential routing run inside the canonical Invocation service, and only then
does :func:`execute_image_generation` post to the gateway. A Binding pin
selects the image model; otherwise the request must name one, and an
unselected model is unavailable rather than guessed.

Generated bytes never enter the Invocation row. The durable Invocation stores
keep every row for the deployment's lifetime (``capability_invocations`` has no
deletion path; see ``quality/durable-table-retention.json``), so a result that
carried the images would grow the database, its WAL and every backup by
megabytes per call. The egress writes each image to an :class:`ImageBlobStore`
and records only a reference, its SHA-256 and its size. Replay reads the bytes
back by reference and checks them against the recorded digest.

The store is a port rather than a table because the durable home for these
bytes, ``canvas_blobs``, belongs to maistro-canvas, which depends on this
package: core cannot write it without reversing that dependency. The consumer
that owns such a table implements this protocol over it.
"""

from __future__ import annotations

import hashlib
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict

from maistro.capabilities.binding import Binding, ResolvedCapabilityProvider
from maistro.capabilities.binding_store import (
    BindingDisabled,
    BindingNotFound,
    BindingScopeDenied,
    BindingStore,
)
from maistro.capabilities.credential_routing import CredentialBackedProvider
from maistro.capabilities.invocation import EffectNotApplied, Invocation, InvocationUsage
from maistro.capabilities.providers.image_gateway import (
    IMAGE_GENERATE_CAPABILITY,
    GeneratedImage,
    ImageGenerationRequest,
    LlmGatewayImageProvider,
    execute_image_generation,
)
from maistro.capabilities.providers.llm_gateway import GatewayEndpoint
from maistro.capabilities.types import Unavailable

if TYPE_CHECKING:
    from maistro.capabilities.effect_context import CapabilityEffectContext


@runtime_checkable
class ImageBlobStore(Protocol):
    """Where generated image bytes live; the Invocation keeps only references."""

    async def put(self, data: bytes, *, media_type: str) -> str:
        """Store ``data`` and return the reference that :meth:`get` accepts.

        Must be safe to repeat with the same bytes, and must not return until
        the bytes are as durable as the Invocation row that will name them.
        """
        ...

    async def get(self, ref: str) -> bytes | None:
        """Return the stored bytes, or ``None`` when the reference is unknown."""
        ...


class InMemoryImageBlobStore:
    """Process-local, content-addressed; for tests and single-process use.

    It is exactly as durable as the process. Pair it only with an in-memory
    Invocation store: a durable row naming bytes this store has since lost
    replays as :class:`ImageBlobUnavailable`, never as a second generation.
    """

    def __init__(self) -> None:
        self._blobs: dict[str, bytes] = {}

    async def put(self, data: bytes, *, media_type: str) -> str:
        del media_type  # the recorded entry carries it; the address is the content
        ref = f"sha256:{hashlib.sha256(data).hexdigest()}"
        self._blobs[ref] = bytes(data)
        return ref

    async def get(self, ref: str) -> bytes | None:
        return self._blobs.get(ref)


class ImageStorageError(EffectNotApplied):
    """The gateway produced images this system could not keep.

    Image generation changes no state outside the bytes it returns, so bytes
    that were never stored mean the effect never reached this system: the
    Invocation terminalizes ``FAILED`` and a later Attempt may retry it,
    exactly as for a gateway that returned nothing.
    """


class ImageBlobUnavailable(RuntimeError):
    """A recorded image can no longer be read back as the bytes it recorded.

    Raised on replay, never answered with a new generation: the Invocation is
    ``COMPLETED``, so producing different bytes under the same ``effect_key``
    would silently change a result the Run already accepted.
    """


class ImageGenerationResult(BaseModel):
    """Governed image outcome plus the Invocation that records it."""

    model_config = ConfigDict(extra="forbid")

    invocation_id: str
    model: str
    images: list[bytes]
    #: The blob-store references, in the same order as ``images``, for a
    #: consumer that should pass images on by reference rather than by value.
    refs: list[str]


async def _require_image_binding(bindings: BindingStore, binding: Binding) -> None:
    # A caller-built Binding is not authority: only the registered record is.
    registered = await bindings.get(binding.binding_id)
    if registered is None:
        raise BindingNotFound(f"Binding {binding.binding_id!r} is not registered")
    if registered != binding:
        raise BindingScopeDenied(
            f"Binding {binding.binding_id!r} does not match its registered definition"
        )
    if binding.capability != IMAGE_GENERATE_CAPABILITY:
        raise BindingScopeDenied(
            f"Binding {binding.binding_id!r} authorizes Capability {binding.capability!r}, "
            f"not {IMAGE_GENERATE_CAPABILITY!r}"
        )
    if binding.disabled:
        raise BindingDisabled(
            f"Binding {binding.binding_id!r} is disabled and cannot authorize effects"
        )


def _usage(provider: LlmGatewayImageProvider, body: dict[str, Any]) -> InvocationUsage:
    return InvocationUsage(
        units="images",
        output_units=len(body["images"]),
        model=provider.name,
        provider="llm-gateway",
    )


async def _stored(blobs: ImageBlobStore, image: GeneratedImage) -> dict[str, object]:
    """Write one image and return the entry the Invocation records for it."""

    try:
        ref = await blobs.put(image.data, media_type=image.media_type)
    except Exception as exc:  # any storage failure: the bytes did not reach us
        raise ImageStorageError(
            f"generated image could not be stored ({type(exc).__name__}: {exc})"
        ) from exc
    return {
        "ref": ref,
        "sha256": hashlib.sha256(image.data).hexdigest(),
        "bytes": len(image.data),
        "media_type": image.media_type,
        "revised_prompt": image.revised_prompt,
    }


async def _read_back(blobs: ImageBlobStore, invocation_id: str, entry: dict[str, Any]) -> bytes:
    ref = str(entry.get("ref") or "")
    data = await blobs.get(ref) if ref else None
    if data is None:
        raise ImageBlobUnavailable(
            f"Invocation {invocation_id!r} recorded image {ref!r}, "
            "which the image blob store does not hold"
        )
    if hashlib.sha256(data).hexdigest() != entry.get("sha256"):
        raise ImageBlobUnavailable(
            f"Invocation {invocation_id!r} recorded image {ref!r}, "
            "but the stored bytes no longer match its digest"
        )
    return data


class ImageGenerationEgress:
    """Cross the one governed image-generation boundary for an effect consumer."""

    def __init__(
        self,
        effects: CapabilityEffectContext,
        *,
        endpoint: GatewayEndpoint,
        blobs: ImageBlobStore,
    ) -> None:
        self._effects = effects
        self._endpoint = endpoint
        self._blobs = blobs

    async def generate(
        self,
        *,
        binding: Binding,
        run_id: str,
        node_run_id: str,
        attempt_id: str,
        effect_key: str,
        request: ImageGenerationRequest,
    ) -> ImageGenerationResult:
        """Run one governed image generation and return the decoded images."""

        await _require_image_binding(self._effects.bindings, binding)
        selected: list[LlmGatewayImageProvider] = []

        async def resolve(candidate: Binding) -> ResolvedCapabilityProvider | Unavailable:
            model = candidate.provider_name or request.model
            if not model:
                return Unavailable(
                    slot=IMAGE_GENERATE_CAPABILITY,
                    reason="neither the Binding nor the request selects an image model",
                )
            selected[:] = [LlmGatewayImageProvider(model=model)]
            return selected[0]

        async def execute(provider: ResolvedCapabilityProvider, payload: Any) -> Any:
            if not isinstance(provider, CredentialBackedProvider):
                raise TypeError("image physical execution requires a Binding-scoped credential")
            endpoint = self._endpoint.model_copy(update={"api_key": provider.credential.api_key})
            images = await execute_image_generation(provider.base, payload, endpoint=endpoint)
            return {"images": [await _stored(self._blobs, image) for image in images]}

        routing = self._effects.credential_routing()
        invocation = await self._effects.invocations.invoke(
            binding=binding,
            run_id=run_id,
            node_run_id=node_run_id,
            attempt_id=attempt_id,
            effect_key=effect_key,
            request=request,
            resolver=routing.resolver(resolve),
            executor=routing.executor(execute),
            usage_from=lambda body: _usage(selected[0], body),
        )
        return await self._result(invocation)

    async def _result(self, invocation: Invocation) -> ImageGenerationResult:
        body = invocation.result if isinstance(invocation.result, dict) else {}
        items = body.get("images")
        entries = (
            [item for item in items if isinstance(item, dict)] if isinstance(items, list) else []
        )
        return ImageGenerationResult(
            invocation_id=invocation.invocation_id,
            model=invocation.binding.provider_name,
            images=[
                await _read_back(self._blobs, invocation.invocation_id, entry) for entry in entries
            ],
            refs=[str(entry["ref"]) for entry in entries],
        )


__all__ = [
    "IMAGE_GENERATE_CAPABILITY",
    "ImageBlobStore",
    "ImageBlobUnavailable",
    "ImageGenerationEgress",
    "ImageGenerationRequest",
    "ImageGenerationResult",
    "ImageStorageError",
    "InMemoryImageBlobStore",
]
